name: My First WorkFlow

on: push    # For multiple triggers -> [push, fork]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "My first Github Actions job"

        - name: List files
          run: ls

        - name: Read file
          run: cat README.md
